from typing import TypedDict, Annotated, List
import operator


class ResearchState(TypedDict):
    # the subject provided by the user
    topic: str

    # Generated by PLANNER: a list of angles/questions to explore
    plan: List[str]

    # Produced by the RESEARCHER: the accumulated research results
    research: Annotated[List[str], operator.add]

    # Produced by the WRITER: the current draft of the report
    draft: str

    # Reviewed by the REVIEWER: their verdict and comments
    review: str
    approved: bool

    # Infinite loop protection
    revision_count: int